[package]
name = "zone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
borsh = { version = "1.1.2", features = ["derive"] } 
solana-program = "1.17.4"

[lib]
crate-type = ["cdylib", "lib"]

